<?php

namespace App\Enums\SelectionProcess;

enum Education: string
{

    case ENSINO_FUNDAMENTAL_COMPLETO =  "ENSINO_FUNDAMENTAL_COMPLETO";
    case ENSINO_FUNDAMENTAL_INCOMPLETO =  "ENSINO_FUNDAMENTAL_INCOMPLETO";

    case ENSINO_MEDIO_COMPLETO =  "ENSINO_MEDIO_COMPLETO";
    case ENSINO_MEDIO_INCOMPLETO =  "ENSINO_MEDIO_INCOMPLETO";

    case ENSINO_SUPERIOR_COMPLETO =  "ENSINO_SUPERIOR_COMPLETO";
    case ENSINO_SUPERIOR_INCOMPLETO =  "ENSINO_SUPERIOR_INCOMPLETO";

    case POS_GRADUACAO_COMPLETO =  "POS_GRADUACAO_COMPLETO";
    case POS_GRADUACAO_INCOMPLETO =  "POS_GRADUACAO_INCOMPLETO";

    case DOUTORADO_COMPLETO =  "DOUTORADO_COMPLETO";
    case DOUTORADO_INCOMPLETO =  "DOUTORADO_INCOMPLETO";

    case CURSO_TECNICO_COMPLETO =  "CURSO_TECNICO_COMPLETO";
    case CURSO_TECNICO_INCOMPLETO =  "CURSO_TECNICO_INCOMPLETO";
}

